### ISSUE TITLE
req.logMessage ?

### ISSUE THREAD

**Issue by matthiasuweberg** [SAP/cf-nodejs-logging-support#11]
Hello, 

in the minimal example the following coding is mentioned: 

` req.logMessage("info", "Hello World will be send");`

Shouldn't it be 
` log.logMessage("info", "Hello World will be send");`

Thanks and kind regards,
Matthias

**Comment by christiand93** [comment]
Hi Matthias,

the library binds the function logMesage(..) to the request object. So it is possible to call req.logMessage(..) or log.logMessage(..). 

The main advantage of using req.logMessage(..) is the tracking of the correlation_id. Log entries generated by using req.logMessage(..) will contain the correlation_id of the corresponding request, while log.logMessage(..) is independent from the request.

This behavior is also described within the [custom-messages](https://github.com/SAP/cf-nodejs-logging-support/blob/master/README.md#custom-messages) section.

Kind regards,
Christian
