### ISSUE TITLE
Avoid publishing dev folders like docs & tools

### ISSUE THREAD

**Issue by SchroederSteffen** [SAP/cf-nodejs-logging-support#137]
Hi,

We noticed that the published package also contains the folders `docs` & `tools` which are only needed for development purposes, but not in production.
Hence, we would like to suggest excluding them from the published package. The package size could be (roughly) halved by that. (Can be tested locally via `npm pack`.)

Especially the `tools` folder causes issues for us, because it includes another `package.json` which some build tools try to install unnecessarily.

I would suggest to use the [files](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files) property of the `package.json` which acts as an include list to avoid publishing any new additional unnecessary files: #138
Of course, the existing `.npmignore` file could also be extended: #139

Please review the suggested PRs and merge either of them.

Cheers,
Steffen

**Comment by christiand93** [comment]
Hi @SchroederSteffen,
thank you for pointing this out and providing the PR(s). I think you're totally right about that. There is no need for shipping any additional docs, tools, samples etc. as part of the package. We will review your suggestion asap.

**Comment by christiand93** [comment]
We have merged #138 and plan to release new minor version update soon.

**Comment by SchroederSteffen** [comment]
Awesome, many thanks! 👍

**Comment by fromagnoli-sap** [comment]
Hi [@SchroederSteffen](https://github.com/SchroederSteffen), we released a new version 6.13.2. Thanks again for your contribution.

**Comment by SchroederSteffen** [comment]
Perfect, thanks! 👍
