### ISSUE TITLE
follow after request

### ISSUE THREAD

**Issue by Shchori** [SAP/cf-nodejs-logging-support#14]
Hi,

Our team develop a new service in Cloud Foundry, the service include 3 Node Js micro-services.
we want to follow after new request between the micro-services, the problem is that the logger change the correlation-id / request-id when we send new request between the micro-services.
there is a way to keep the same correlation-id/request-id for all the forwarding requests ?

Thanks,
Nir Shchori

**Comment by nicklas-dohrn** [comment]
Our Library works with the following code for correlation tracking:
```js
    if (req.headers["X-CorrelationID"] != null) {
        logObject.correlation_id = req.headers["X-CorrelationID"];
    } else if (req.headers["x-vcap-request-id"] != null) {
        logObject.correlation_id = req.headers["x-vcap-request-id"];
    } else {
        logObject.correlation_id = uuid();
    }
```
All you need to do is to keep the correlationid/requestid field populated in your new request header when you need to keep track of a request.

**Comment by Shchori** [comment]
Thank you for the support!
