### ISSUE TITLE
Local logging of express and application

### ISSUE THREAD

**Issue by WorkAlexGahr** [SAP/cf-nodejs-logging-support#16]
Hi ,

i found out that when try to log my requests with a pattern like 
`setLogPattern('[{{level}}] {{written_at}} - {{msg}}') `
it works fine for all normal logs when i use it in the application.
However when i use it with express like

`service.use(log.logNetwork);`

The message will be always empty which leads to logs like :
 [info] 2017-12-06T13:54:16.718Z - [{{msg}}]

Better would be if we either would write nothing instead of {{msg}} or we could make a condition to use one format for express logging and one format for normal logs. 

Is this possible or is this a bug?

**Comment by nicklas-dohrn** [comment]
Hi Alex,
The behaviour was indeed unwanted, we made a mistake handling parsing of pattern identifiers, which were not set as variables.
I made a new version yesterday (2.2.0) which incorporates the fix to this problem and introduces the possibility to define constant overrides to network logging, so you can now use custom (constant) messages:
```js
log.overrideNetworkField("msg", "this is a networklog");
```
This will override msg in ALL following network logs with "this is a network log".
We do not distinguish between user and network logs, so we cannot easily implement different log patterns for them.
Does this meet your requirements? 
Please let me know if there are issues with the new functionality.
Greeting,
Nicklas
