### ISSUE TITLE
Log pattern placeholder in output message

### ISSUE THREAD

**Issue by dKaulig** [SAP/cf-nodejs-logging-support#17]
Hello,

i've got an issue when defining a log pattern.

For example:
I define the log pattern:
```js
log.setLogPattern("{{written_at}} - [{{level}}] {{correlation_id}} {{msg}} {{request}}");
```

A normal 
```js
log.logMessage("info", "I am listening on port 1337"); 
```
would result in an output like:

> 2017-12-08T10:28:08.653Z - [info] {{correlation_id}} I am listening on port 1337 {{request}}

A express log output would look like:

> 2017-12-08T10:28:12.323Z - [info] 985fd5cd-eab1-40ea-8221-2725f585ecf4 {{msg}} /red/

The problem is, the "writeLogToConsole" function just replaces the placeholder with keys which are in the logObject.

A solution cloud be:
[https://github.com/SAP/cf-nodejs-logging-support/blob/master/cf-nodejs-logging-support-core/log-core.js](log-core.js)

Add
```js
output = output.replace(/{{.*?}}\s?/g, '');`
```
after the for loop.

Like:
```js
	var output = pattern;
	for (var key in options.meta) {
		if (typeof (options.meta[key]) === "object" && validObject(options.meta[key])) {
			output = output.replace('{{' + key + '}}', JSON.stringify(options.meta[key]));
		} else {
			output = output.replace('{{' + key + '}}', options.meta[key]);
		}
	}
	output = output.replace(/{{.*?}}\s?/g, '');
	return output;
```

**Comment by christiand93** [comment]
Hello dKaulig, 

we're currently rewriting our code, which will fix this behavior.

Best regards,
Christian

**Comment by WorkAlexGahr** [comment]
Hello Christan,

maybe you introduce mustache for the templates. Its fast and would do the job completly.
Regards
Alex

**Comment by christiand93** [comment]
Hello dKaulig, Alex,

we fixed this problem by replacing all placeholders, even those without a corresponding field. 

In addition we checked out mustache, but decided to keep things simple and use our own implementation to avoid additional dependencies.

Best regards,
Christian
