### ISSUE TITLE
logMessage is not using the customFields in v7

### ISSUE THREAD

**Issue by InfiniteXyy** [SAP/cf-nodejs-logging-support#181]
## Problem
`logger.logInfo` will not use the `customFields`, if we setup the logger with `Map` config
`logger.logInfo` will throw an error when using `getCustomFields`, if we setup the logger with `object` config

## Possible Root Cause
https://github.com/SAP/cf-nodejs-logging-support/blob/main/src/lib/logger/logger.ts#LL184C29-L184C35

Here is using `Object.assign` for a map object, which will always return `{}`

## Minimum reproduction
```js
import Logger from 'cf-nodejs-logging-support';

/* Scene 1: config the logger with Map object (the designed way) */
// component_name and id are not carried
const logger = Logger.createLogger(
  new Map([
    ['componnet_name', 'demo'],
    ['component_id', '0001'],
  ])
);

logger.info('test');

/* Scene 2: config the logger with Pure object (the designed way) */
// component_name and id are carried
const logger2 = Logger.createLogger({
  component_name: 'demo',
  component_id: '0001',
});

logger2.info('test');

// but if we call `getCustomFields`, will throw a runtime error
logger2.getCustomFields();

```

Or try it in [stackbliz](https://stackblitz.com/edit/stackblitz-starters-fhrgxk?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=package.json,index.js,package-lock.json&title=node.new%20Starter)

**Comment by christiand93** [comment]
Hi @InfiniteXyy,

thank you for reporting this bug. I'm working on a fix and will provide an update as soon as possible. 

WIP: https://github.com/SAP/cf-nodejs-logging-support/compare/main...fix-custom-fields 

Kind regards,
Christian

**Comment by christiand93** [comment]
The fix is merged. I will prepare a new release shortly.

Kind regards,
Christian
