### ISSUE TITLE
Support for own correlation id

### ISSUE THREAD

**Issue by WorkAlexGahr** [SAP/cf-nodejs-logging-support#19]
We implemented a polling in our server, so we actually generate there we generate requests which do not originate from any other incoming requests. 
I would love if i could now still generate or set a correlation id for the logger for our req object.

Is this somehow possible?

**Comment by sapmathias** [comment]
Can we reopen this issue?

We are bound to a governmental specification, which defines a `correlationId` coming in via `POST` body.

**Comment by christiand93** [comment]
In this case you need to extract the `correlationId` from the body and provide it to the `req` object (which acts as context object) via:
```
// extract correlation_id from body
var id = ... 
req.setCorrelationId(id);
```
