### ISSUE TITLE
Availability in npm registry

### ISSUE THREAD

**Issue by jainbasil** [SAP/cf-nodejs-logging-support#2]
Hi,

I would like to consume this module from npm registry. But npm install fails. Is this available in repository?

Regards, 
Jain

**Comment by christiand93** [comment]
Hi Jain,

we are still waiting for an internal authorization to publish our module via npm. It is all about licenses and rights.

Kind regards,
Christian

**Comment by I073141** [comment]
Thanks Christian for the reply. Do you know how long it takes to get approval ?

Regards,
Nishil

**Comment by christiand93** [comment]
Hello Nishil,

we got the approval this morning and are planning to release the module via npm within the next week.

Kind regards,
Christian

**Comment by I073141** [comment]
Hello Christian,

Please let me know when the module is available on NPM.

Thanks,
Nishil

**Comment by christiand93** [comment]
Hello Nishil,

the module is now available on npm.

Kind regards,
Christian
