### ISSUE TITLE
Dependency on npm required?

### ISSUE THREAD

**Issue by UweKlinger** [SAP/cf-nodejs-logging-support#22]
Hi,

is it really required to have a dependency on npm? 

This adds a load of code to any package using cf-nodejs-logging-support.

Maybe you want to have it as devDependency only?

It was introduced by:  https://github.com/SAP/cf-nodejs-logging-support/commit/14d54f8e579673fad8ca491fdcb327098e0785bd

**Comment by christiand93** [comment]
Hi,

thank you for the report. I have removed this dependency in version 3.0.8.

Christian
