### ISSUE TITLE
using `setCustomFieldsTypeConversion` functionality

### ISSUE THREAD

**Issue by bawaji94** [SAP/cf-nodejs-logging-support#227]
While setting custom fields for logging I noticed that the custom values logged where being stringified. Upon looking at the [documentation](https://sap.github.io/cf-nodejs-logging-support/configuration/custom-fields-format#custom-fields-format), I came across `setCustomFieldsTypeConversion` functionality to `retain` the data types of the custom log values. However, the function seems to be `undefined`.

I installed the latest version (v7.3.0) of `cf-nodejs-logging-support` using npm.

**Comment by christiand93** [comment]
Hi @bawaji94,
The feature is already implemented and merged. I will create a new release v7.4.0 this week.
I'm sorry for the inconvenience.
Kind regards,
Christian

**Comment by christiand93** [comment]
Hi @bawaji94,
Version 7.4.0 is now available via [github](https://github.com/SAP/cf-nodejs-logging-support/releases/tag/v7.4.0) and [npm](https://www.npmjs.com/package/cf-nodejs-logging-support/v/7.4.0). 

Kind regards,
Christian
