### ISSUE TITLE
Question on correlation_id and request_id

### ISSUE THREAD

**Issue by petar-iv** [SAP/cf-nodejs-logging-support#25]
My understanding for correlation_id (having in mind [the description](https://github.com/SAP/cf-java-logging-support/blob/v2.1.5/cf-java-logging-support-core/beats/request-metrics/docs/fields.asciidoc#correlation_id)) is that it is a value which is the same for all requests to different applications that take part in the processing of a single logical transaction. And if there isn't such a logical transaction, then I would not expect a value for this field. But in [the config](https://github.com/SAP/cf-nodejs-logging-support/blob/v3.0.11/config.js#L281-L289) I see that if the request header *x-corelationid* is not present, then the value of request_id will be taken. Why?

Here are the reasons why I think this is a bit confusing:
- Lets have a standalone request. The logs will state that the current request is part of a logical transaction (there is a value for the field) when actually it isn't. Of course, one may say that it is a transaction consisting of a single request, but does the correlation_id bring benefit in that case? We already have the request_id.
- There are 2 properties with the same value: correlation_id and request_id and this is just not necessary.

Now there is always a value for correlation_id, but not always for request_id (from [the config](https://github.com/SAP/cf-nodejs-logging-support/blob/v3.0.11/config.js#L107-L113), if the *x-vcap-request-id* header is not present). But to me it seems more logical to always have a request_id (since we are logging during the processing of a request) and to not always have a correlation_id (since not always the request will be a part of a logical transaction involving multiple requests).

Regarding filtering: one can use request_id, and only if he/she knows the correlation id to filter by correlation_id.

Many thanks and best regards
Petar

**Comment by Apps16** [comment]
Hi Petar,

I have noticed the below behaviour when the correlation id was not coming in the request. At the application logs level, the correlation field was shown as '-'. But we wanted some id to be present in the logs such that we can map the logs for the particular request.

![correlation_id](https://user-images.githubusercontent.com/17724185/44777274-d498df80-ab97-11e8-8705-c654165be8b0.png)

This id will be used in the application which will be internally called also. 

In java logging library which we are using also has the behaviour of replacing the correlation with request id when not found. We wanted to replicate the same in the node as well.

Regards,
Aparna

**Comment by Apps16** [comment]
Hi Petar,

We have noticed the below behaviour when the correlation id was not coming in the request. At the application logs level, the correlation field was shown as '-'. But we wanted some id to be present in the logs such that we can map the logs for the particular request.

![correlation_id](https://user-images.githubusercontent.com/17724185/44777455-51c45480-ab98-11e8-8c51-ba6943c8d071.png)
This id will be passed on to the application which will be internally called also.

In java logging library which we are using also has the behaviour of replacing the correlation with request id when not found. We wanted to replicate the same in the node logging as well.

Regards,
Aparna
