### ISSUE TITLE
Integers in custom fields will be rendered as string

### ISSUE THREAD

**Issue by UweKlinger** [SAP/cf-nodejs-logging-support#26]
Hi,

we want to do analysis over integer values from custom fields using Kibana. But Kibana recognizes the value as string (which cannot be changed) and it is not possible to build charts on it. 

There reason for this is, that the logger converts any value of a custom field into a string using JSON.stringify().

Can you change the code so the logger will keep numbers as numbers. Logstash/Kibana should be able to handle this correctly.

It happens in `cf-nodejs-logging-support-core/log-core.js`: 
```
            if (!((typeof customFields[key]) == "string")) {
                logObject.custom_fields[key] = JSON.stringify(customFields[key]);
            } else {
                logObject.custom_fields[key] = customFields[key];
            }
```

Thanks & Best regards,
Uwe Klinger
SAP SE

**Comment by KarstenSchnitter** [comment]
In our Logstash/Kibana solution all custom fields are deliberately converted to Strings. This decision was made to ensure proper operation on name conflicts: In Elasticsearch each field has a fixed type. This type is either determined by a mapping or created on the fly from the first document. Documents with mismatching types cannot be ingested. As we have no control over the field names we decided to treat all custom fields as string type (keyword). 

The use-case for custom fields as you suggest points to metrics and/or monitoring. This is currently unsupported. We are evaluating different strategies to provide better support of such use-cases.

**Comment by UweKlinger** [comment]
Ok, thanks for your answer. We will look into alternative approaches.
