### ISSUE TITLE
How to set correlationId when consuming from RabbitMQ

### ISSUE THREAD

**Issue by sapmathias** [SAP/cf-nodejs-logging-support#27]
Hey, what is the best practice to set the `correlationId` (or logContext) when the message is not received from a HTTP Request, but from a message Queue like RabbitMQ?

Also how to make sure that asynchronous (and therefore 'parallel') consumption occuring in one instance of the microservice can still distinguish different `correlationIds`?

**Comment by christiand93** [comment]
Hi, to create logs for other than HTTP requests you can create correlation context objects. We recently added a [description](https://github.com/SAP/cf-nodejs-logging-support#correlation-context-objects) for this functionality. These objects can be used in parallel and allow to set custom CorrelationIDs via ```ctx.setCorrelationId(...)```.
