### ISSUE TITLE
Build failed with botkit-middleware-dialogflow module

### ISSUE THREAD

**Issue by khajam30** [SAP/cf-nodejs-logging-support#28]
Dear experts 
I am trying to build extend my jabber app adding  module "botkit-middleware-dialogflow": "^2.0.4" , but it returns the below error could you please help find the cause of the issue 

Thanks 

4:04:35 PM (Builder) Build of "/CiscoJabber/myjabber" started.
4:04:44 PM (DIBuild) Build of "/CiscoJabber/myjabber" in progress.
4:04:45 PM (DIBuild) Service provisioning for module: '/myjabber'[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------
4:05:13 PM (DIBuild) > grpc@1.17.0 install /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc> node-pre-gyp install --fallback-to-build --library=static_librarygyp ERR! configure error gyp ERR! stack Error: ENOENT: no such file or directory, open '/home/vcap/app/META-INF/resources/nodejs/aggr.pem'gyp ERR! stack     at Object.fs.openSync (fs.js:646:18)gyp ERR! stack     at Object.fs.readFileSync (fs.js:551:33)gyp ERR! stack     at readCAFile (/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:466:15)gyp ERR! stack     at download (/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:438:22)gyp ERR! stack     at /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:185:19gyp ERR! stack     at /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:5)gyp ERR! System Linux 4.15.0-39-genericgyp ERR! command "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node" "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"gyp ERR! cwd /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpcgyp ERR! node -v v8.9.1gyp ERR! node-gyp -v v3.6.2gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)node-pre-gyp ERR! System Linux 4.15.0-39-genericnode-pre-gyp ERR! command "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node" "/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"node-pre-gyp ERR! cwd /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpcnode-pre-gyp ERR! node -v v8.9.1node-pre-gyp ERR! node-pre-gyp -v v0.12.0node-pre-gyp ERR! not ok Failed to execute '/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! grpc@1.17.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the grpc@1.17.0 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR!     /home/vcap/app/META-INF/cache/8.9.1/.npm/_logs/2019-01-13T12_05_22_461Z-debug.log
4:05:17 PM (Builder) Build of /CiscoJabber/myjabber failed.

**Comment by nicklas-dohrn** [comment]
Dear khajam,
I briefly looked into your trace and the module "botkit-middleware-dialogflow", and i can see no correlation with this module so far, so i would like you to point out to us in which way exactly we might be able to help you with this issue?
Sincerely, Nicklas Dohrn

**Comment by khajam30** [comment]
Thanks Nicklas,
I am new to this and would appreciate your suggestion.
I have successfully  deployed botkit module on SAP cloud platform, but as soon as I add entry of "botkit-middleware-dialogflow": "^2.0.4" in to the package.json and build the app, it throws the error.

Why it has to throw the error only when the middleware module is added to the package.json file?

Following is the complete code 
*************
//Server.js //

/*eslint no-console: 0*/
"use strict";

const Botkit = require('botkit');
const xml = require('@xmpp/xml');
/*const dialogflowMiddleware = require('botkit-middleware-dialogflow')({
  //keyFilename: './mybot-service-key.json',  // service account private key file from Google Cloud Console
  token: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
});*/

var controller = Botkit.jabberbot({
    json_file_store: './jabberbot/'
});

var bot = controller.spawn({
    client: {
        jid: 'jbot',
        password: 'xxxxx',
        host: "xxxxxxxxx",
        port: 5222,
        preferred: "PLAIN"
    }
});
/*Controller.middleware.receive.use(dialogflowMiddleware.receive);
Controller.hears(['Default Welcome Intent'], 'direct_message', dialogflowMiddleware.hears, function(bot,  message) {
  replyText = message.fulfillment.text;  // message object has new fields added by Dialogflow
  bot.reply(message, replyText);
});*/

controller.hears('hello', 'direct_message', function(bot, message) {
    bot.reply(message, 'Hello yourself!');
    });
    
controller.on('direct_message', function(bot, message) {
        bot.reply(message, 'I got your direct message. You said, "' + message.text + '"');
    });

*************************************************
//Package.json//
{
  "dependencies": {
  	"botkit": "^0.7.0"
  },
  "description": "my description",
  "devDependencies": {
    "jest": "^23.6.0",
    "jest-junit": "^5.2.0"
  },
  "files": [],
  "main": "server.js",
  "name": "myjabberBot",
  "scripts": {
    "test": "jest --config jest.json",
    "test-coverage": "jest --coverage --config jest.json",
    "start": "node server.js"
  },
  "engines": {
    "node": "8.x"
  },
  "version": "1.0.0"
}

*****************************************

**Comment by khajam30** [comment]
Correction.....
Package.json 

{
  "dependencies": {
  	"botkit": "^0.7.0",
  	"botkit-middleware-dialogflow": "^2.0.4"
  },
  "description": "my description",
  "devDependencies": {
    "jest": "^23.6.0",
    "jest-junit": "^5.2.0"
  },
  "files": [],
  "main": "server.js",
  "name": "myjabberBot",
  "scripts": {
    "test": "jest --config jest.json",
    "test-coverage": "jest --coverage --config jest.json",
    "start": "node server.js"
  },
  "engines": {
    "node": "8.x"
  },
  "version": "1.0.0"
}

**Comment by christiand93** [comment]
Question is not related to this library
