### ISSUE TITLE
API for reading correlation_id

### ISSUE THREAD

**Issue by mlenkeit** [SAP/cf-nodejs-logging-support#3]
Is there a public API to read the correlation_id, e.g. to pass it to another service (service-to-service communication)?

**Comment by nicklas-dohrn** [comment]
You can get the correlation id from the header of the corresponding request.
It is called X-CorrelationID.
You can find our reading of this value in:
https://github.com/SAP/cf-nodejs-logging-support/blob/master/cf-nodejs-logging-support-express/log-express.js

**Comment by mlenkeit** [comment]
But I don't want to copy that code, especially since when there is no correlation id, a new one is generated.
The corresponding Java package has an API for that: https://github.com/SAP/cf-java-logging-support/blob/67ca983aacf798f78935124eae7e4c4367520451/cf-java-logging-support-core/src/main/java/com/sap/hcp/cf/logging/common/LogContext.java#L95

**Comment by nicklas-dohrn** [comment]
we attach our logging object onto the req object so you can also get the correlation idea via req.logObject.correlation_id.

**Comment by christiand93** [comment]
You can get the correlation_id now by calling getCorrelationId() on the request object. See documentation.
