### ISSUE TITLE
Offer Java-like log methods

### ISSUE THREAD

**Issue by mariograf** [SAP/cf-nodejs-logging-support#31]
Hi CF-Logging-Team, 

in Java (especially SLF4j) logger method names typically already include log severity, e.g. logger.info(message), etc. The same applies for some Node logging libs, e.g. Winston. 

It would be great if you could offer similar methods in your Node lib, as well. Currently, there is only the possibility to log via logger.logMessage(severity,message,custom_fields).

Some of my colleagues implemented a small express middleware as workaround, which does this in the following way:

```js
const log = (req, res, next) => {
  req.logger = {
    log: (level, msg, custom_fields) => {
      req.getCorrelationObject().logMessage(level, msg, custom_fields);
    },
    silly: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('silly', msg, custom_fields);
    },
    debug: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('debug', msg, custom_fields);
    },
    verbose: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('verbose', msg, custom_fields);
    },
    info: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('info', msg, custom_fields);
    },
    warn: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('warn', msg, custom_fields);
    },
    error: (msg, custom_fields) => {
      req.getCorrelationObject().logMessage('error', msg, custom_fields);
    }
  };
  next();
};
```
Thank you in advance and best regards, 
Mario

**Comment by christiand93** [comment]
Hi Mario,

we started to implement this feature and will provide it in the next version of the library.

Best regards,
Christian

**Comment by nicklas-dohrn** [comment]
Hi Mario,
we implemented this feature and the requested convenience methods are now supported. (v5.0.0 and higher)
Best regards,
Nicklas

**Comment by mariograf** [comment]
Thank you!
