### ISSUE TITLE
Logs not visible in node js debuggers

### ISSUE THREAD

**Issue by Shubham-2k17** [SAP/cf-nodejs-logging-support#37]
I am not able to see logs in Chrome Devtools & other Node Js debuggers.

On inspection I found that `cf-nodejs-logging-support` is using `process.stdout.write` instead of `console.log/error/warn/....`.

`process.stdout.write` output isn't sent over v8-inspector debug protocol socket. Thus, logs are not visible in any debugger.

https://github.com/winstonjs/winston/issues/981
https://github.com/microsoft/vscode/issues/19750

1. How can we use debuggers with `cf-nodejs-logging-support`?
2. If not, Is there any alternative which can be used?

**Comment by christiand93** [comment]
Hi, 

I've added a setter `log.setSinkFunction()` which replaces the internal call to `process.stdout.write` by a call to a provided function. The first argument of the sink function is the logging level and the second is the output string. 

Example usage:
```
log.setSinkFunction((level, output) => {
    console.log(output);
});
```

The `log.setSinkFunction()` is available as of version 5.3.0
