### ISSUE TITLE
Write VCAP_APPLICATION data in log message

### ISSUE THREAD

**Issue by anklei** [SAP/cf-nodejs-logging-support#38]
to match functionality of the java library and to enable future use cases, some data from VCAP_APPLICATION shall be written in the logs as well.In particular:

- "application_id";
- "application_name";
- "instance_index";
- "space_id";
- "space_name";
- "organization_id";
- "organization_name

Java implementation as reference:
https://github.com/SAP/cf-java-logging-support/blob/8d835d382bf08614226b823d835cd21a6952e992/cf-java-logging-support-core/src/main/java/com/sap/hcp/cf/logging/common/VcapEnvReader.java#L32

**Comment by christiand93** [comment]
Hi, the majority of the mentioned fields is already configured, but some of them have differing names:

- "application_id": currently printed as "component_id"
- "application_name": currently printed as "component_name"
- "instance_index": currently printed as "component_instance"
- "space_id": existing
- "space_name": existing
- "organization_id": existing, has to be updated to be read from VCAP_APPLICATION 
- "organization_name": existing, has to be updated to be read from VCAP_APPLICATION 

How do we deal with the duplicated fields (component_id, component_name, component_instance)? Can we drop them?

**Comment by christiand93** [comment]
As of version 5.3.1 `organization_id` and `organization_name` are read from VCAP_APPLICATION.
