### ISSUE TITLE
Memory leak when using logger

### ISSUE THREAD

**Issue by Shubham-2k17** [SAP/cf-nodejs-logging-support#39]
When trying to send 10000 requests with delay of 10ms between each request, memory consumption increases from less than 10 MB to 100MB and doesn't decrease afterwards. It was tested on code sample at https://github.com/SAP/cf-nodejs-logging-support#with-nodejs-http

**Comment by christiand93** [comment]
Hi,
I've reproduced your experiment and monitored the heap size before and after running 10000 requests. This results in a difference of around 0.7 MB. After running another 10000 requests, heap size did not increase any further. However, windows task manager lists the node process at around 60 to 120 MB after the requests were performed, which does not really decrease afterwards. Performing more requests results in some fluctuation, but doesn't really increase the overall memory consumption. This behavior seems to be related to the native memory allocation of node.js.

**Comment by Shubham-2k17** [comment]
seems like some issue in our code.
