### ISSUE TITLE
Feature: log plain text for local testing

### ISSUE THREAD

**Issue by mlenkeit** [SAP/cf-nodejs-logging-support#4]
The [`cf-java-logging-support`](https://github.com/SAP/cf-java-logging-support) module has separation between capturing logs and printing them to the console, allowing the user (i.e. the developer) to determine the output format (e.g. JSON vs. plain text).

Especially for development and local testing, plain text logs are much easier to read then their JSON representation.

Is there any chance you can add functionality to specify the output format?

Thanks,
Max

**Comment by christiand93** [comment]
We implemented this feature in version 1.0.0

Kind regards,
Christian

**Comment by WolfgangTheilmann** [comment]
I guess this issue can be closed, right?
