### ISSUE TITLE
Contextualize logs

### ISSUE THREAD

**Issue by marikaner** [SAP/cf-nodejs-logging-support#40]
I would like to log some context information for every log. Currently, I am only interested in the custom logs. I can add this information to the custom fields like this:

```js
const logger = require('cf-nodejs-logging-support');
logger.info('Information log.', { CONTEXT: 'context'});
```

but I don't want to add the context manually to every log statement. What I would like to do instead would be something like this:

```js
const { createLogger } = require('cf-nodejs-logging-support');
const logger = createLogger({ CONTEXT: 'context'});
logger.info('Information log.');
```

I would like to create an instance of a logger, that has its own context. This currently does not seem to be possible with this library. I tried to add a wrapper for this, but I don't see a clean way to achieve this. Am I overseeing something?

**Comment by christiand93** [comment]
Hi, contextual (child) loggers are now available, see [child loggers](https://github.com/SAP/cf-nodejs-logging-support#child-loggers) and [custom fields](https://github.com/SAP/cf-nodejs-logging-support#custom-fields) sections for a description.

Regards,
Christian
