### ISSUE TITLE
Why is there duplicate information in the logs?

### ISSUE THREAD

**Issue by marikaner** [SAP/cf-nodejs-logging-support#41]
When logging the lib, there are information like e. g. `component_name` that are already represented in the logs as `cf_app_name`. Why does this duplication exist and is it documented anywhere?

**Comment by KarstenSchnitter** [comment]
Hi, can you elaborate, how you find `cf_app_name`? This library does not generate an output of that name. It wraps the log message of your code in a JSON object, that contains several other fields, especially `component_name`, but not `cf_app_name`. However, you might see a `cf_app_name` when consuming your logs via `cf logs`. This information is provided by the CF cli in a separate way. Currently CF does not ensure, that the component name is shipped on all channels. That is why the information is emitted by our library.
