### ISSUE TITLE
Correlation id independent of request

### ISSUE THREAD

**Issue by yishn** [SAP/cf-nodejs-logging-support#42]
In the past we have used `log.createCorrelationObject()` to create a child logger that logs a correlation id even though it didn't come from an incoming HTTP request. Is it possible to do that in v6.0.0, as it seems like you have removed the function?

**Comment by christiand93** [comment]
Hi, you can use ```log.createLogger()``` instead. This function provides a child logger object, which contains a correlation id. If the correlation id cannot be inherited from the parent logger (in this case ```log```), a new one will be generated.

**Comment by yishn** [comment]
Thanks a lot, seems to be working!
