### ISSUE TITLE
Different log patterns for contextual loggers

### ISSUE THREAD

**Issue by abh1kg** [SAP/cf-nodejs-logging-support#43]
Now that child loggers are supported in this nifty little module, would it be possible to have a provision to define a custom log pattern per child logger?
I am expecting something like:
```
const globalLogger = require('cf-nodejs-logging-support');
// pattern for global logging
globalLogger.setLogPattern(
  '{{written_at}}  {{type}} - {{level}} - {{msg}}'
);
const childLogger = globalLogger.createLogger();
child.setLogPattern(
  '{{written_at}}  {{type}} - {{level}} - {{msg}} - {{custom_fields}}'
);
```

**Comment by christiand93** [comment]
Hi, we don't have plans to support customizable log patterns for child loggers. Setting log patterns is a deprecated feature and will probably be removed in future. We've decided to keep the focus on logging in standardized JSON format.

Regards,
Christian
