### ISSUE TITLE
logMessage is undefined on v6.0.0

### ISSUE THREAD

**Issue by Alexandru11** [SAP/cf-nodejs-logging-support#44]
Currently using the logger in a back-end service deployed to CF. Version v5.3.2 works perfectly . 
Unfortunately, latest version seems to throw an undefined error for this.logMessage . Tracing the source to \\node_modules\\cf-nodejs-logging-support\\cf-nodejs-logging-support-winston\\winston-transport.js:20:18 .
Would like to use latest for _added contextual loggers and custom field registration_.

**Comment by christiand93** [comment]
Hi, thank you for your report. This error has been fixed in version v6.0.0. Unfortunately the new contextual/child logger features cannot be used in combination with winston. When using winston our library attaches as _transport_ and cannot spawn child loggers.
