### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by devtechcorp** [SAP/cf-nodejs-logging-support#56]
Hello,

in the README it should say redacted and not reducted. https://www.npmjs.com/package/cf-nodejs-logging-support/v/3.0.1#sensitive-data-reduction 

Kind regards,

a user

**Comment by christiand93** [comment]
Hi,

thank you for reporting, it was fixed in later versions. However, the functionality itself is called 'reduction' instead of 'redaction' at the top of the readme. I will fix that.

Best regards,
Christian
