### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by submetu** [SAP/cf-nodejs-logging-support#65]
Hi can we get typings for `
- error
- warn
- info
- verbose
- debug
- silly

That would be great, thanks!

**Comment by nicklas-dohrn** [comment]
So far, our whole library is written using javascript functionality, with no typescript specific coding.
I see the benefit for having these typings, as it would really help to clarify which typings can be used.

At the moment, I am quite reluctant to add more dependencies to our library, as we have had only minimal issues with our minimal dependency approach.
At the moment, the typings are created programmatically and are also able to change on runtime, that may prove hard to do with typings for typescript, but as I am not an expert on typescript, I may be proven wrong on this.

Sorry for my late answer,
Nicklas

**Comment by nazarkulyk** [comment]
Actually typings would be really welcome as we write our backends in typescript too.
Option is to use cloud-sdk/util logger to log out to kibana ob BTP.

Simple adding index.d.ts would do trick, we also can provide simple pool request with it...

**Comment by kalmanl** [comment]
I agree, this would be great and enhancement our experience
we have many teams in our product using Typescript

I don't think this would be a big change
1. add to `tsconfig` -> `compilerOptions` the option "declaration": true,
2. export types, can be done by adding to index.TS which I see is already done
then when building the compiler will add types to  `index.d.ts`

**Comment by christiand93** [comment]
As of version 7 TypeScript is supported and typings are available.
