### ISSUE TITLE
cf-nodejs-logging-support and @sap/logging

### ISSUE THREAD

**Issue by sbarzaghialteaup** [SAP/cf-nodejs-logging-support#69]
Hi,
Is there any kind of correlation between cf-nodejs-logging-support and @sap/logging?
Regards,
Sam

**Comment by nicklas-dohrn** [comment]
If I got all the relations correctly, these two libraries serve different purposes.
If you use either the sap application logging or sap cloud logging service, I would strongly advise to use this library,
as this library is build especially to work best with these services.

**Comment by sbarzaghialteaup** [comment]
Hi @nicklas-dohrn,
Yes we are using scp application logging service and the cf-nodejs-logging-support as reccommended in the official application log documentation. Currently we have no issue using it.
However I cannot see any big different purpose  with @sap/logging, the package handles scp CF logs too.
Regards,
Sam

**Comment by nicklas-dohrn** [comment]
If you are using application logging, please keep using this library and only this library for logging, as we try our best to assure, that logs written by this library will be parsed and ingested correctly in our logging stack.
We need to be quite restrictive with our parsing of customer logs, so users are not able to expose sensitive data via carelessly named log fields.

I cannot really comment on the usecase of the @sap/logging library, but looking at the code, I would say it serves a different purpose as our library, and feature wise, I do not see any benefit for you switching to it, as I will soon also provide an update to support sap-passport headers if you might need that.

**Comment by sbarzaghialteaup** [comment]
Hi,

For your info I arrived to @sap/logging with this link:
https://www.npmtrends.com/@sap/logging-vs-cf-nodejs-logging-support

Thank you for you support.

Best Regards,
Sam
