### ISSUE TITLE
tenant_id still missing in the request logger

### ISSUE THREAD

**Issue by ilyes-mansour** [SAP/cf-nodejs-logging-support#72]
Hello everyone,

Regarding the readme, the tenant_id must be automatically available in the request.logger.logObject  when running the application in multi-tenancy context (e.g. CAP CDS in my case), but the value is always '-' even in kibana.

Currently, as a workaround, i am retrieving the tenantID from the request itself : req.authInfo.identityZone and adding it to the request logger : req.logger.setTenantId() for each request, so it can be added in kibana tenant_id field properly.

Can you check why the tenant_id is remaining not available please, 

And by the way, if you judge adding a fallBack in the config.js to check the tenant_id from identityZone and use it in case no value provided will be also great ^^'. The subdomain is also available and could be retrieved automatically also in req.authInfo.subdomain :).

B.R.
Ilyes

**Comment by christiand93** [comment]
Hi Ilyes,

currently we do not provide support for logging the `tenant_id` and `tenant_subdomain` from security contexts out-of-the-box. This is why our library implements `tenant_id` and `tenant_subdomain` as settable fields, which should provide a certain amount of flexibility here.
I suggest to use an [express middleware](https://expressjs.com/en/guide/using-middleware.html) function to set the `tenant_id` and `tenant_subdomain` automatically based on the `req.authInfo` object:

```js
app.use((req, res, next) => {
    req.logger.setTenantId(req.authInfo.identityZone);
    req.logger.setTenantSubdomain(req.authInfo.subdomain);
    next();
});
```

Please let me know if this is a sufficient solution for your use case. 

Kind regards,
Christian

**Comment by ilyes-mansour** [comment]
Hi Christian,
thank you for responding :).
Yes this is exactly what we are currently doing,
i haven't thought that it wasn't implemented because of security requirements, now i understand 😄.
Best Regards,
Ilyes

**Comment by HeneryHawk** [comment]
Hi Christian,

just to be sure.
Setting the tenant id and subdomain via `req.logger.setTenantId` and `req.logger.setTenantSubdomain` does not cause that `logNetwork` logs the tenant id and subdomain as well.
When the above middleware is mounted, the tenant id and subdomain will continue to be empty or the initial value `-` in the request logs.

Is this correct?

We use another middleware before logNetwork, which sets the tenant id as header field of the request. Here the tenant id is logged in the request logs.

```javascript
app.use((req, res, next) => {
    req.headers.tenantid = req.authInfo.identityZone;

    next();
});

app.use(logger.logNetwork);

app.use((req, res, next) => {
    req.logger.setTenantId(req.authInfo.identityZone);
    req.logger.setTenantSubdomain(req.authInfo.subdomain);

    next();
});
```

Kind regards,
Simon
