### ISSUE TITLE
pino support ...

### ISSUE THREAD

**Issue by ClaudiuOctavianMuresan** [SAP/cf-nodejs-logging-support#8]
I was wondering if we might get in the future any integration with pino logging framework (https://github.com/pinojs/pino) as an alternative to winston.

**Comment by nicklas-dohrn** [comment]
Currently, our module is heavily depending on winston for writing logs to logstash.
We are currently investigating possibilities to provide transports for pino or similar modules, but we cannot make any promises so far.

**Comment by ClaudiuOctavianMuresan** [comment]
Thanks.

**Comment by nicklas-dohrn** [comment]
We removed the winston module completely from our library as a dependency and we do not plan to add more transports to this package, because this is not our focus and will likely blur the usage of this package.
