### ISSUE TITLE
ReferenceError: defaultConfig is not defined

### ISSUE THREAD

**Issue by gk-patel** [SAP/cf-nodejs-logging-support#82]
Hi, 

I have installed this library in my project. It works fine when there is only one version installed. 
But if we use two versions, in a node-inside-node, i.e. where we have a node_modules package at the partent and subFolder level - each containing two slightly different versions (6.6 and 6.7 respectively), then the project breaks with the following error, 

" ReferenceError: defaultConfig is not defined "

And I was able to make the project work by putting "var" in front of the defaultConfig varaiable on [this line](https://github.com/SAP/cf-nodejs-logging-support/blob/master/index.js#L8). Also, I am not able to understand why the project works without the defaultConfig being defined at the first place - but I am no Node expert, maybe you can throw some light on this matter.

**Comment by christiand93** [comment]
Hi,
thank you for creating this issue and contributing PR #83 to fix it. As explained in the PR, the missing `var` causes the problem when enabling strict mode. The fix is part of release version 6.8.0.
Christian
