### ISSUE TITLE
Switch off the INFO log on KIBANA

### ISSUE THREAD

**Issue by inayath-m** [SAP/cf-nodejs-logging-support#86]
Have enabled the cf-nodejs-logging-support in our application. And setLoggingLevel to WARN however in the KIBANA, we are  seeing INFO messages  as well along with WARN.  The documentation is not clear on the structured log messages. The java based approach has clear information.  Need to know, how to, have the structure messages through NODE JS. And also how to disabled ROOT level messages.

**Comment by christiand93** [comment]
Hi,
thank your question. Per default, request logs get written with log level `info`. This means, you will not see any request logs written by our library when changing the logging level to `warn` using `log.setLoggingLevel("warn")`.

However, if you want to write request logs with another log level, you can change it via:
```js
log.setRequestLogLevel("warn")
```

Please note, that this only affects logs written by this library. Changing logging level thresholds or request log level has no effect on router logs. Logs written by our library can be identified by the `layer` field being set to `[NODEJS]`.

This is also documented in the [Request Logs](https://sap.github.io/cf-nodejs-logging-support/general-usage/request-logs#setting-the-log-level-for-requests) section.
