### ISSUE TITLE
Switch logLevel 

### ISSUE THREAD

**Issue by T1mey** [SAP/cf-nodejs-logging-support#91]
Hi, 

I read the through the docs but I couldn't find the information how to set the log level to another value without redeployment.
I would expect that the is a env variable the module is looking for...

I saw the function for setting log level via header param for a specific request but this not helping me.

**Comment by KarstenSchnitter** [comment]
This library allows dynamic configuration of log levels by adding an http header to the request. It needs to contain a JWT, that configures the log level to be applied. The documentation can be found here: https://github.com/SAP/cf-nodejs-logging-support/blob/master/docs/advanced-usage/04-dynamic-logging-level-threshold.md. 

You can implement a different mechanism, if you do not want to use the JWT approach. The extension point of the library is the setLoggingLevel function.

**Comment by T1mey** [comment]
@KarstenSchnitter Thanks for the quick reply. Is the JWT approach working when CF is connected to a custom IdP ?

**Comment by KarstenSchnitter** [comment]
The JWT approach is independent of the IdP. You need to configure the public key to be used for JWT validation in the environment variable `DYN_LOG_LEVEL_KEY`.
